language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c 'create database sendit_test;' -U postgres
  - export DB_URL="dbname='sendit_test' host='localhost' port='5432' user='postgres' password=''"

script:
  - pytest --cov=app/

after_success:
  - coveralls