language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before script:
  - psql -c 'create database sendit;' -U postgres
  - export DB_URL="dbname='sendit' host='localhost' port='5432' user='postgres' password=''"
  - export FLASK_ENV="testing"

script:
  - pytest --cov=app/

after_success:
  - coveralls
  